### ISSUE TITLE
Hardware Specs?

### ISSUE THREAD

**Issue by KrishnaPG** [BlueBrain/Tide#219]
Thank you sharing this code. The video looks inspiring. We are planning to setup similar system for our research meetings. How to achieve it?

Wondering if you could throw some light on the hardware configurations, setup and any others useful details used in constructing the system shown in the video. Are those typical touch monitors or specialized hardware etc. details.

Thanks.

**Comment by rdumusc** [comment]
Thank you for your interest. Tide can run on a variety of hardware, ranging from a single TV screen to a array of 3D stereo projectors. Note that currently the screens/projectors must form a regular grid (all of the same resolution and size).
The installation that you see in the video is a 4x3 matrix of thin-bezel Planar displays with an infrared touch frame mounted around the ensemble. Other touch technologies should work as well as long as they support the TUIO protocol and can deliver a single input to the application.
The wall in question is driven by a single (semi-recent) dual-core server with 3 GPUs, each connected to 4 displays. Tide doesn't have high CPU / GPU demands unless you open a lot a movies or high-resolution pixel streams. It is designed to run on multiple servers too for larger installations (we are currently in the process of deploying an 8 projectors + 8 servers 3D wall).
To get a perfectly accurate frame swap in multi-GPU configurations, Nvidia Quadro + GSync cards can be used, although that's not a requirement for 2D display walls.

**Comment by KrishnaPG** [comment]
Thanks much @rdumusc
