### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by MengjiaoH** [BlueBrain/Tide#273]
Hi,
I am trying to compiling with the master branch. But it can't built successfully. I attached the error. Wondering if I did something wrong.

Thanks so much.

CMakeFiles/core-ActivityLoggerTests.dir/core/ActivityLoggerTests.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > json::dump<ActivityLogger>(ActivityLogger const&)':
/home/powerwall/mnt/ssh/shell/home/sci/powerwall/Tide/tide/core/json/templates.h:66: undefined reference to `json::serialize(ActivityLogger const&)'
collect2: error: ld returned 1 exit status
tests/cpp/CMakeFiles/core-ActivityLoggerTests.dir/build.make:151: recipe for target 'tests/cpp/core-ActivityLoggerTests' failed
make[2]: *** [tests/cpp/core-ActivityLoggerTests] Error 1
CMakeFiles/Makefile2:6991: recipe for target 'tests/cpp/CMakeFiles/core-ActivityLoggerTests.dir/all' failed
make[1]: *** [tests/cpp/CMakeFiles/core-ActivityLoggerTests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by rdumusc** [comment]
Hello,
You're right, it looks like rest/serialization.cpp required by this unit test is not compiled when TIDE_ENABLE_REST_INTERFACE is disabled (which I assume is your case). I'll push a fix for it soon. Unfortunately our CI only builds with all options enabled so this type of bugs tend to go unnoticed, thanks for reporting.

**Comment by rdumusc** [comment]
fixed in #274
