### ISSUE TITLE
URGENT: Tide blocking travis queue

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/Tide#62]
Hi,

Travis is experiencing some problems with the mac osx builds, and this seems to have a knock-on effect on all BlueBrain builds. The end result is that my NeuroM build has been hanging for hours. Could someone please kill the relevant builds? Also, the travis people suggest it might be an idea to limit the number of concurrent Tide builds to 1 or 2. Apparently this can be done from the settings, but I have no access: https://travis-ci.org/BlueBrain/Tide/settings

Here's the feedback I got from travis support:

> Thanks for reaching out and sorry for this issue.
> 
> I had a look at your account and here is what is happening: you currently have 5 jobs on the BlueBrain/Tide repo queued on our OS X infrastructure and we currently have [an outage on this specific infrastructure](https://www.traviscistatus.com/incidents/bwp879gf6bc5). The result is that your queue is blocked because of this. Sorry for the inconvenience.
> 
> To mitigate this situation I can offer you the following workaround. You could limit the number of concurrent builds on the BlueBrain/Tide repo to 1 or 2. This setting is available in [the repository settings](https://travis-ci.org/BlueBrain/Tide/settings). Then it would ensure that there is still room for build jobs queued on other infrastructures. Let me know if you want to set this up and I will happily cancel your builds that are blocking your queue.
> 
> Thank you for your understanding and we will follow-up upon your reply.

**Comment by rdumusc** [comment]
Hi,
Sorry for the late reply. I did as you suggested and limited the number of concurrent builds for Tide to 2. However, even if we add this limit to every Bluebrain project this will not be enough to ensure that the builds are fast for the Travis OSX, I will respond in more details to your email.
